# Global configuration for PurpleIRC
# How often we check to see if a bot is connected to the IRC server. This is in server ticks (There 20 ticks in one sec).
conn-check-interval: 1000
# Startup an ident server
enable-ident-server: false
# How often we check the channel user list
channel-check-interval: 100
# Chat messages support standard Bukkit color codes using '&#'. 
# The following macro tokens are also supported.
#  %WORLD% 
#  %NAME% 
#  %DISPLAYNAME% 
#  %CHANNEL% 
#  %MESSAGE%
#  %KICKER%
#  %TOPIC%
#  %REASON%
#  %GROUP% - Requires Vault if you want to use this.
#  %PLAYERPREFIX% - Requires Vault if you want to use this.
#  %PLAYERSUFFIX% - Requires Vault if you want to use this.
#  %GROUPSUFFIX% - Requires Vault if you want to use this.
#  %GROUPPREFIX% - Requires Vault if you want to use this.
#  %WORLDCOLOR% - Requires Multiverse.
#  %PARTY% - mcMMO party channel name
#  %FACTIONMODE% - Faction chat mode (all, ally, enemy)
#  %FACTIONTAG%  - Faction tag name
#  %HEROCHANNEL% - HeroChat channel name
#  %HERONICK% - HeroChat channel nick
#  %HEROCOLOR% - HeroChat channel color
#  %TITANCHANNEL% - TitanChat channel name
#  %TITANCOLOR% - TitanChat channel color
#  %WORLDALIAS% - World alias name
#  ReportRTS ticket: %MESSAGE%, %MODNAME% %RTSNAME% %RTSWORLD% %TICKETNUMBER%
message-format:
  # Message templates for game to IRC messages
  console-chat: '&0[&5Server&0] %MESSAGE%' 
  game-action: '&0[&2%WORLD%&0] ***%NAME%&0 %MESSAGE%'
  game-pchat: '&0[&2%WORLD%&0]<%NAME%&0> %MESSAGE%'
  # Notification to player when sending a private message to an IRC user
  game-pchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  game-chat: '&0[&2%WORLD%&0]<%NAME%&0> %MESSAGE%'
  game-death: '&0[&2%WORLD%&0] %MESSAGE%'  
  game-kick: '&0[&2%WORLD%&0] %MESSAGE%'
  game-join: '&0[&2%WORLD%&0] %MESSAGE%'
  game-quit: '&0[&2%WORLD%&0] %MESSAGE%'
  game-command: '&0[&2%WORLD%&0] Command detected by %NAME%: %COMMAND% %PARAMS%'
  # Message template for "/irc send" to IRC message
  game-send: '&0[&2%WORLD%&0]<%NAME%&0> %MESSAGE%' 
  # Essentials messages
  ess-player-afk: '&0[&2%WORLD%&0] %NAME% &0is now AFK' 
  ess-player-not-afk: '&0[&2%WORLD%&0] %NAME% &0is no longer AFK' 
  # Message templates for IRC to game messages
  irc-action: '&f[&4IRC&f] ***%NAME%&f %MESSAGE%'
  irc-chat: '&f[&4IRC&f]<%NAME%&f> %MESSAGE%'  
  irc-pchat: '&dPrivate message: &f[&4IRC&f]<%NAME%&f> %MESSAGE%' 
  # Notification to user when sending a private message to a player
  irc-pchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  # Notification to user when sending a message to a specific hero channel
  irc-hchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  irc-join: '&f[&4IRC&f] %NAME%&f has joined %CHANNEL%.'
  irc-kick: '&f[&4IRC&f] %NAME%&f was kicked from %CHANNEL% by %KICKER%. (Reason- %REASON%)'
  irc-part: '&f[&4IRC&f] %NAME%&f has left %CHANNEL%.'  
  irc-quit: '&f[&4IRC&f] %NAME%&f has left %CHANNEL%. (Reason: %REASON%)'  
  irc-topic: '&f[&4IRC&f] Topic changed by %NAME%&0: %TOPIC%.'  
  irc-nickchange: '&f[&4IRC&f] %OLDNICK% is now known as %NEWNICK%.'  
  irc-mode: '&f[&4IRC&f] %NAME%&f %MODE% on %CHANNEL%'
  irc-notice: '&f[&4IRC&f] [notice(%CHANNEL%)] %NOTICE% '
  # Message template for Clevernotch bot to IRC messages
  clever-send: '&0[&4BOT&0]<%NAME%&0> %MESSAGE%' 
  # Message templates for mcMMO to IRC messages
  mcmmo-admin-chat: '&0[admin:%WORLD%&0]<%NAME%&0> %MESSAGE%'    
  mcmmo-party-chat: '&0[party:%PARTY%&0]<%NAME%&0> %MESSAGE%'
  # Message templates for FactionChat to IRC messages
  faction-public-chat: '&0[%FACTIONMODE%] &0[%FACTIONTAG%&0]<%NAME%&0> %MESSAGE%'  
  faction-ally-chat: '&0[%FACTIONMODE%] &0[%FACTIONTAG%&0]<%NAME%&0> %MESSAGE%'  
  faction-enemy-chat: '&0[%FACTIONMODE%] &0[%FACTIONTAG%&0]<%NAME%&0> %MESSAGE%'  
  # Message template for Herochat to IRC messages
  hero-chat: '&0[%CHANNEL%&0]<%NAME%&0> %MESSAGE%'
  # Message templates for IRC to Herochat messages
  irc-hero-action: '&f[&3IRC&f] ***%NAME%&f %MESSAGE%'
  irc-hero-chat: '&f[&3IRC&f]<%NAME%&f> %MESSAGE%'  
  irc-hero-join: '&f[&3IRC&f] %NAME%&f has joined %CHANNEL%.'
  irc-hero-kick: '&f[&3IRC&f] %NAME%&f was kicked from %CHANNEL% by %KICKER%. (Reason- %REASON%)'
  irc-hero-part: '&f[&3IRC&f] %NAME%&f has left %CHANNEL%.'  
  irc-hero-topic: '&f[&3IRC&f] Topic changed by %NAME%&f: %TOPIC%.'  
  # Message template for TitanChat to IRC messages
  titan-chat: '&0[%CHANNEL%&0]<%NAME%&0> %MESSAGE%'
  # Message templates for IRC to TitanChat messages
  irc-titan-chat: '&f[&3IRC&f]<%NAME%&f> %MESSAGE%'
  # Invalid IRC command message
  invalid-irc-command: "I'm sorry '%NICK%' I can't do that. Type '%CMDPREFIX%help' for a list of commands I might respond to."
  no-perm-for-irc-command: "I'm sorry '%NICK%' you are not authorized to do that. Type '%CMDPREFIX%help' for a list of commands I might respond to."
  rts-notify: '[RTS] <%NAME%> %MESSAGE%'
  irc-hero-channels:
      Global: '&f[G]&f[IRC]%PLAYERPREFIX%%NAME%&f %MESSAGE%'
  broadcast-message: '[Broadcast] <%NAME%> %MESSAGE%'
  broadcast-console-message: '[Broadcast] <Console> %MESSAGE%'
  # Defaults below take effect when user joins IRC and matching player is offline
  default-player-suffix: ''
  default-player-prefix: ''
  default-group-suffix: ''
  default-group-prefix: ''
  default-player-world: 'world'
  default-player-group: ''  
# Prevent game colors from appearing in IRC
strip-game-colors: false
# Prevent IRC colors from appearing in game
strip-irc-colors: false
# Add IRC names to in-game tab list
custom-tab-list: false
# Nothing to see here
custom-tab-prefix: '[IRC] '
# IRC nick must be an exact match to a player name for token expanding
nick-exact-match: true
Debug: false