# Global configuration for PurpleIRC
# How often we check to see if a bot is connected to the IRC server. This is in server ticks (There 20 ticks in one sec).
conn-check-interval: 1000
# Startup an ident server
enable-ident-server: false
# How often we check the channel user list
channel-check-interval: 100
# Chat messages support standard Bukkit color codes using '&#'. 
# The following macro tokens are also supported.
#  %WORLD% 
#  %NAME% 
#  %DISPLAYNAME% 
#  %CHANNEL% 
#  %MESSAGE%
#  %KICKER%
#  %TOPIC%
#  %REASON%
#  %GROUP% - Requires Vault if you want to use this.
#  %PLAYERPREFIX% - Requires Vault if you want to use this.
#  %PLAYERSUFFIX% - Requires Vault if you want to use this.
#  %GROUPSUFFIX% - Requires Vault if you want to use this.
#  %GROUPPREFIX% - Requires Vault if you want to use this.
#  %WORLDCOLOR% - Requires Multiverse.
#  %PARTY% - mcMMO party channel name
#  %FACTIONMODE% - Faction chat mode (all, ally, enemy)
#  %FACTIONTAG%  - Faction tag name
#  %HEROCHANNEL% - HeroChat channel name
#  %HERONICK% - HeroChat channel nick
#  %HEROCOLOR% - HeroChat channel color
#  %TITANCHANNEL% - TitanChat channel name
#  %TITANCOLOR% - TitanChat channel color
#  %WORLDALIAS% - World alias name
#  ReportRTS ticket: %MESSAGE%, %MODNAME% %RTSNAME% %RTSWORLD% %TICKETNUMBER%
#  %TOWNYCHANNEL% - Towny channel name
#  %TOWNYCHANNELTAG% - Towny channel tag name
#  %TOWNYMSGCOLOR% - Towny message color
#  %JOBS% - Player jobs
#  %JOBS% - Player jobs shortened
message-format:
  # Message templates for game to IRC messages
  console-chat: '&r[&5Server&r] %MESSAGE%' 
  game-action: '&r[&2%WORLD%&r] ***%NAME%&r %MESSAGE%'
  game-pchat: '&r[&2%WORLD%&r]<%NAME%&r> %MESSAGE%'
  # Notification to player when sending a private message to an IRC user
  game-pchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  game-chat: '&r[&2%WORLD%&r]<%NAME%&r> %MESSAGE%'
  game-death: '&r[&2%WORLD%&r] %MESSAGE%'  
  game-kick: '&r[&2%WORLD%&r] %MESSAGE%: %REASON%'
  game-join: '&r[&2%WORLD%&r] %MESSAGE%'
  game-quit: '&r[&2%WORLD%&r] %MESSAGE%'
  game-command: '&r[&2%WORLD%&r] Command detected by %NAME%: %COMMAND% %PARAMS%'
  # Message template for "/irc send" to IRC message
  game-send: '&r[&2%WORLD%&r]<%NAME%&r> %MESSAGE%' 
  # Essentials messages
  ess-player-afk: '&r[&2%WORLD%&r] %NAME% &ris now AFK' 
  ess-player-not-afk: '&r[&2%WORLD%&r] %NAME% &ris no longer AFK' 
  # Message templates for IRC to game messages
  irc-action: '&r[&4IRC&r] ***%NAME%&r %MESSAGE%'
  irc-chat: '&r[&4IRC&r]<%NAME%&r> %MESSAGE%'  
  irc-pchat: '&dPrivate message: &r[&4IRC&r]<%NAME%&r> %MESSAGE%' 
  # Notification to user when sending a private message to a player
  irc-pchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  # Notification to user when sending a message to a specific hero channel
  irc-hchat-response: ' &6-> &7%TARGET%: %MESSAGE%'
  irc-join: '&r[&4IRC&r] %NAME%&r has joined %CHANNEL%.'
  irc-kick: '&r[&4IRC&r] %NAME%&r was kicked from %CHANNEL% by %KICKER%. (Reason- %REASON%)'
  irc-part: '&r[&4IRC&r] %NAME%&r has left %CHANNEL%.'  
  irc-quit: '&r[&4IRC&r] %NAME%&r has left %CHANNEL%. (Reason: %REASON%)'  
  irc-topic: '&r[&4IRC&r] Topic changed by %NAME%&r: %TOPIC%.'  
  irc-nickchange: '&r[&4IRC&r] %OLDNICK% is now known as %NEWNICK%.'  
  irc-mode: '&r[&4IRC&r] %NAME%&r %MODE% on %CHANNEL%'
  irc-notice: '&r[&4IRC&r] [notice(%CHANNEL%)] %NOTICE% '
  # Message template for Clevernotch bot to IRC messages
  clever-send: '&r[&4BOT&r]<%NAME%&r> %MESSAGE%' 
  # Message templates for mcMMO to IRC messages
  mcmmo-admin-chat: '&r[admin:%WORLD%&r]<%NAME%&r> %MESSAGE%'    
  mcmmo-party-chat: '&r[party:%PARTY%&r]<%NAME%&r> %MESSAGE%'
  mcmmo-chat: '&r[mcMMO]<%NAME%&r> %MESSAGE%'
  # Message templates for FactionChat to IRC messages
  faction-public-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'  
  faction-ally-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'  
  faction-enemy-chat: '&r[%FACTIONMODE%] &r[%FACTIONTAG%&r]<%NAME%&r> %MESSAGE%'  
  # Message template for Herochat to IRC messages
  hero-chat: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  hero-action: '&r[&2%CHANNEL%&r] ***%NAME%&r %MESSAGE%'
  # Message templates for IRC to Herochat messages
  irc-hero-action: '&r[&3IRC&r] ***%NAME%&r %MESSAGE%'
  irc-hero-chat: '&r[&3IRC&r]<%NAME%&r> %MESSAGE%'  
  irc-hero-join: '&r[&3IRC&r] %NAME%&r has joined %CHANNEL%.'
  irc-hero-kick: '&r[&3IRC&r] %NAME%&r was kicked from %CHANNEL% by %KICKER%. (Reason- %REASON%)'
  irc-hero-part: '&r[&3IRC&r] %NAME%&r has left %CHANNEL%.'  
  irc-hero-quit: '&r[&3IRC&r] %NAME%&r has left %CHANNEL%.'  
  irc-hero-topic: '&r[&3IRC&r] Topic changed by %NAME%&r: %TOPIC%.'  
  # Message template for TitanChat to IRC messages
  titan-chat: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  # Message templates for IRC to TitanChat messages
  irc-titan-chat: '&r[&3IRC&r]<%NAME%&r> %MESSAGE%'
  # Message templates for Towny to IRC messages
  towny-channel-chat: '&r%TOWNYCHANNELTAG%[%TOWNYCHANNEL%]<%NAME%&r> %MESSAGE%'
  # Invalid IRC command message
  invalid-irc-command: "I'm sorry '%NICK%' I can't do that. Type '%CMDPREFIX%help' for a list of commands I might respond to."
  no-perm-for-irc-command: "I'm sorry '%NICK%' you are not authorized to do that. Type '%CMDPREFIX%help' for a list of commands I might respond to."
  rts-notify: '[RTS:New] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-complete: '[RTS:Complete] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-claim: '[RTS:Claim] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-unclaim: '[RTS:Unclaim] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-held: '[RTS:Held] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  rts-assign: '[RTS:Assign] #%TICKETNUMBER% <%NAME%> %MESSAGE%'
  # Jobs seperator
  jobs-separator: ', '
  # Message format per hero channel. From game to IRC. For use with @hchat.
  irc-hero-channels:
      Global: '&r[G]&r[IRC]%PLAYERPREFIX%%NAME%&r %MESSAGE%'
  # Message format per hero channel. From game to IRC. Overrides hero-chat template.
  hero-channels:
      Global: '&r[%CHANNEL%&r]<%NAME%&r> %MESSAGE%'
  # Emote message format per hero channel. From game to IRC. Overrides hero-action template.
  hero-action-channels:
      Global: '&r[&2%CHANNEL%&r] ***%NAME%&r %MESSAGE%'
  broadcast-message: '[Broadcast] <%NAME%> %MESSAGE%'
  broadcast-console-message: '[Broadcast] <Console> %MESSAGE%'
  # Defaults below take effect when user joins IRC and matching player is offline
  default-player-suffix: ''
  default-player-prefix: ''
  default-group-suffix: ''
  default-group-prefix: ''
  default-player-world: 'world'
  default-player-group: ''  
# Format for the @list command in IRC
list-format: '&r[&9Minecraft&r] Online (%COUNT%/%MAX%): %PLAYERS%'
list-separator: '&r, '
list-player: '%GROUPPREFIX%%NAME%'
# Prevent game colors from appearing in IRC
strip-game-colors: false
# Prevent IRC colors from appearing in game
strip-irc-colors: false
# Add IRC names to in-game tab list
custom-tab-list: false
# Nothing to see here
custom-tab-prefix: '[IRC] '
# IRC nick must be an exact match to a player name for token expanding
nick-exact-match: true
Debug: false