name: PurpleIRC
version: 0.0.2
description: Bukkit IRC Bot
author: cnaude
main: me.cnaude.plugin.PurpleIRC.PIRCMain
commands:
    irc:
        description: Various irc commands
        usage: |
         /<command> reloadbot ([bot])- Reload the bot config and reconnect
         /<command> reloadbotconfig ([bot]) - Reload bot config without reconnecting
         /<command> connect ([bot]) - Connect to configured IRC server
         /<command> disconnect ([bot]) - Disconnect from configured IRC server
         /<command> listbots - List loaded bots
         /<command> list ([bot]) ([channel]) - List users in a channel
         /<command> op [bot] [channel] [user(s)] - Op user(s) in a channel
         /<command> deop [bot] [channel] [user(s)] - DeOp user(s) in a channel
permissions:
  'irc.reload':
    description: Gives player access to the /irc reload.
    default: op
  'irc.reloadbot':
    description: Gives player access to the /irc reloadbot.
    default: op
  'irc.reloadbotconfig':
    description: Gives player access to the /irc reloadconfig.
    default: op  
  'irc.reconnect':
    description: Gives player access to the /irc reconnect.
    default: op
  'irc.message.chat':
    description: Receive IRC chat messages.
    default: true
  'irc.message.gamechat':
    description: Send game chat to IRC
    default: true
  'irc.message.action':
    description: Receive IRC chat actions (/me).
    default: true
  'irc.listbots':
    description: Gives player access to the /irc listbots command.
    default: op
  'irc.list':
    description: Gives player access to the /irc list command.
    default: op  